### ISSUE TITLE
[ui] : Create Session Details Screen

### ISSUE THREAD

**Issue by brianwachira** [droidconKE/droidconKE2022ReactNative#13]
- Create Session Details Screen as per the guideline - [Session Details Screen Design Adobe XD Link](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/09ac0874-4933-4982-9e2e-b5d2c82d6c5f/specs/)
- Follow contribution guidelines laid out in our [contribution guide](https://github.com/droidconKE/droidconKE2022ReactNative/blob/develop/CONTRIBUTING.md)

**Additional context**

![Screenshot 2022-09-12 at 23 36 34](https://user-images.githubusercontent.com/28436092/189754468-b34d91c4-2495-42de-9f6d-22b50157894c.png)

**Comment by mog-rn** [comment]
@brianwachira can I work on this?

**Comment by brianwachira** [comment]
> @brianwachira can I work on this?

please do @Mogakamo 
make sure to follow contribution and style guidelines
All the best!

**Comment by mog-rn** [comment]
Thanks

**Comment by mog-rn** [comment]
@brianwachira how can I also join the slack workspace?

**Comment by brianwachira** [comment]
> @brianwachira how can I also join the slack workspace?

We have recently created a contributer's group on **Telegram**
You are welcome!
https://t.me/+bJGp4hqa4i40NTY0

**Comment by mog-rn** [comment]
ok thanks. Let me join

**Comment by DeroMuli** [comment]
Can I pick this up @brianwachira  @Mogakamo

**Comment by brianwachira** [comment]
> Can I pick this up @brianwachira @Mogakamo

All the best man!
**PS** : The event is 11 days from now 🥲 so let's try finish this issue ASAP 😁
