### ISSUE TITLE
[ui] : create speakers screen 

### ISSUE THREAD

**Issue by brianwachira** [droidconKE/droidconKE2022ReactNative#14]
Create Speakers Screen as per the guideline - [Speakers Screen Design Adobe XD Link](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/ff847474-c6b6-44a2-bb46-0acdffa33f9a/specs/)

Follow contribution guidelines laid out in our [contribution guide](https://github.com/droidconKE/droidconKE2022ReactNative/blob/develop/CONTRIBUTING.md)

**Additional context**

![Screenshot 2022-09-13 at 10 22 36](https://user-images.githubusercontent.com/28436092/189837392-4c94dff4-bfb3-46ca-bc7f-010752310ac0.png)

**Comment by DeroMuli** [comment]
I think I can pick this up @brianwachira .

**Comment by brianwachira** [comment]
> I think I can pick this up @brianwachira .

All the best!
Incase you encounter another one that you would like to contribute please feel free to assign yourself

**Comment by brianwachira** [comment]
@DeroMuli We have recently created a contributer's group on **Telegram**
You are welcome!
https://t.me/+bJGp4hqa4i40NTY0
