### ISSUE TITLE
[ui] : create feedback screen

### ISSUE THREAD

**Issue by brianwachira** [droidconKE/droidconKE2022ReactNative#16]
Create Feedback Screen as per the guideline - [Feedback Screen Design Adobe XD Link](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/1ef2f9cd-d83b-4618-8f29-655f3a9483ae/specs/)

Create Success Modal  For Feedback Screen as per the guideline - [Feedback Screen Design Adobe XD Link](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/1de29b30-29d7-4847-9a5d-90a60ff44249/specs/)

Follow contribution guidelines laid out in our [contribution guide](https://github.com/droidconKE/droidconKE2022ReactNative/blob/develop/CONTRIBUTING.md)

**Additional context**

- Feedback Screen

![Screenshot 2022-09-13 at 10 29 10](https://user-images.githubusercontent.com/28436092/189838513-c0d4aabf-13b6-4341-94e0-d41b864d7e56.png)

- Feedback Sent Screen

![Screenshot 2022-09-13 at 10 31 14](https://user-images.githubusercontent.com/28436092/189838694-977f2e1c-e8cc-46b9-9fdd-0969d8f92f6e.png)

**Comment by DeroMuli** [comment]
I can pick this up @brianwachira . I don't know how to assign myself  a task  : (

**Comment by brianwachira** [comment]
> I can pick this up @brianwachira . I don't know how to assign myself a task : (

Yeah, it seems people are having a hard time assigning themselves a task. Lemme look into it.

Lemme assign you,
All the best!
