### ISSUE TITLE
[ui] : create About Screen

### ISSUE THREAD

**Issue by brianwachira** [droidconKE/droidconKE2022ReactNative#17]
Create About Screen as per the guideline - [About Screen Design Adobe XD Link](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/c87e6ded-5f2e-4f62-81f1-3940e677d79f/specs/)

Follow contribution guidelines laid out in our [contribution guide](https://github.com/droidconKE/droidconKE2022ReactNative/blob/develop/CONTRIBUTING.md)

**Additional context**

![image](https://user-images.githubusercontent.com/28436092/189839457-ad0b5ae7-26e3-4fa0-9322-e4e1c73819e3.png)

**Comment by makunomark** [comment]
@brianwachira I would like to pick this up.

**Comment by makunomark** [comment]
Rough week @brianwachira, I will leave it open for anyone else to pick up before clearing my week.

**Comment by brianwachira** [comment]
> Rough week @brianwachira, I will leave it open for anyone else to pick up before clearing my week.

Hi fam, sorry about that :(
It is okay :)

**Comment by devKiratu** [comment]
Hi @brianwachira, I'd like to give this a try. Kindly assign me

**Comment by devKiratu** [comment]
Thanks!

**Comment by brianwachira** [comment]
> Thanks!

You are welcome!
Make sure to follow through with the contribution and styling guidelines. All the best!
