### ISSUE TITLE
[ui] : create share Feed modal

### ISSUE THREAD

**Issue by brianwachira** [droidconKE/droidconKE2022ReactNative#20]
- Create **Share Feed Modal** that shares Feed from the [Feed Screen](https://github.com/droidconKE/droidconKE2022ReactNative/issues/8)
- Use the guideline - [Share Feed Modal Design Adobe XD Link](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/f5f3abf2-9384-460a-bac7-544c49648c0c/specs/)
- Follow contribution guidelines laid out in our [contribution guide](https://github.com/droidconKE/droidconKE2022ReactNative/blob/develop/CONTRIBUTING.md)

**Additional context**

![image](https://user-images.githubusercontent.com/28436092/189843982-90fb3a51-4d62-4e06-8ba8-4636a4cbf274.png)

**Comment by DeroMuli** [comment]
I think I can pick this up. I need to make some  PRs for hacktoberfest 😂 @brianwachira

**Comment by orama254** [comment]
hello @DeroMuli 

I feel like this issue is dependent on issue #8 .

Is there a way you can implement it without needing it to depend on the issue?

**Comment by DeroMuli** [comment]
I could work on it and test it using storybook @orama254
