### ISSUE TITLE
[intergration] : storybook

### ISSUE THREAD

**Issue by brianwachira** [droidconKE/droidconKE2022ReactNative#22]
- Integrate the storybook with the app in a way that contributors can build and test UI components isolated from the business logic and context of the app. 
- It will allow you to test whatever you are building on the browser, independently from the app logic.

**Additional context**
You can check out Storybook's + React Native walkthrough from their [docs](https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/)

**Comment by makunomark** [comment]
I'd like to pick this up :-)
