### ISSUE TITLE
[Feature] State: Add and test out redux for async actions

### ISSUE THREAD

**Issue by makunomark** [droidconKE/droidconKE2022ReactNative#28]
**Is your feature request related to a problem? Please describe.**
There's an [existing setup ](https://github.com/droidconKE/droidconKE2022ReactNative/pull/27) of redux but it's simple and tested for synchronous scenarios.

**Describe the solution you'd like**
Using react-toolkit, please add support for async operations. For a high level guide, check out [this blog](https://hybridheroes.de/blog/2021-01-08-redux-toolkit-react-native/).

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DeroMuli** [comment]
I think ill pick this up @makunomark

**Comment by DeroMuli** [comment]
Hi , I cant seem to understand this task well. Should i create an [createAsyncThunk](https://hybridheroes.de/blog/2021-01-08-redux-toolkit-react-native/) function  and fetch some data from the backend. Is the backend ready ? What data should I fetch ? @makunomark

**Comment by makunomark** [comment]
At the time of creation. I thought we would need to handle thunk separately. 
Turns out RTK has Thunk already added. 

Think we can close this?

**Comment by DeroMuli** [comment]
I think we should close this @makunomark
