### ISSUE TITLE
Add src directory to hold app logic

### ISSUE THREAD

**Issue by makunomark** [droidconKE/droidconKE2022ReactNative#30]
**Is your feature request related to a problem? Please describe.**
This feature request does not originate from a problem (just yet). We already set up a folder structure in a [previous PR](https://github.com/droidconKE/droidconKE2022ReactNative/pull/3) - it's elegant. It currently looks like this:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/5811391/190556442-346fc8b2-eb0d-4a83-a177-807b0cd3ab68.png">

As we add more and more modules, this is bound to grow and may make our root component hard to understand. 

**Describe the solution you'd like**
IMO, introduction of a `src/`, where our app structure live in, may make the root folder a little easier to understand.
<img width="392" alt="image" src="https://user-images.githubusercontent.com/5811391/190556310-cebcabce-5576-4c2e-aae8-cabde2841fcc.png">

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by brianwachira** [comment]
I like the idea. I am in for it
