### ISSUE TITLE
Header component content shifts off screen

### ISSUE THREAD

**Issue by devKiratu** [droidconKE/droidconKE2022ReactNative#44]
**Describe the bug**
When the app is run on an android device, in the *logged in state*, the profile picture component of the header is slightly pushed off-screen 

**To Reproduce**
1. Run the app locally and scan the QR code using your android device. You can also scan the `Development app` QR code available on the `README.md` file of this repository.
2. On the home screen, press `LOG IN` followed by `GO TO TABS` button
3. You will notice the profile picture component/icon is slightly off screen, when on the `Home tab`

**Expected behavior**
The header component should be inside the screen with a uniform horizontal margin. See the design mockup below:   

![Screenshot 2022-10-10 at 10-10-13 Mobile](https://user-images.githubusercontent.com/59362946/194814364-cb923f77-973a-486e-920d-d8944ebf4c68.png)

**Screenshots**
Below is the screenshot showing the error   

![Screenshot 2022-10-10 at 10-17-41 WhatsApp Image 2022-10-10 at 10 14 48 jpeg (JPEG Image 606 × 1280 pixels) — Scaled (55%)](https://user-images.githubusercontent.com/59362946/194815313-7e74f16a-69ea-48e7-8565-f50b31c42b2d.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: [OPPO A12, model CPH2083]
 - OS: [Android 9, ColorOS version 6.1.2]

**Additional context**
N/A

**Comment by devKiratu** [comment]
@brianwachira I'd like to take up this issue

**Comment by brianwachira** [comment]
Alright, all the best!
