### ISSUE TITLE
Extract Header Component into a Resuable Component

### ISSUE THREAD

**Issue by devKiratu** [droidconKE/droidconKE2022ReactNative#45]
**Is your feature request related to a problem? Please describe.**
The header component is similar across different screens. This will result in repetition of code, violating the DRY principle

**Describe the solution you'd like**
Extract the code into a reusable component, such that any change or improvement will be done from one place

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by devKiratu** [comment]
@brianwachira I'd like to take up this issue and run with it

**Comment by brianwachira** [comment]
Alright, all the best!
