### ISSUE TITLE
Extract the code for Oganized By Section into a Reusable Component

### ISSUE THREAD

**Issue by devKiratu** [droidconKE/droidconKE2022ReactNative#46]
**Is your feature request related to a problem? Please describe.**
The `Organized By` section is similar across different screens. This will result in repetition of code, violating the DRY principle

**Describe the solution you'd like**
Extract the code into a reusable component, such that any change or improvement will be done from one place

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by devKiratu** [comment]
@brianwachira I'd like to take up this issue

**Comment by brianwachira** [comment]
Alright, all the best!
