### ISSUE TITLE
[UI]Create Authentication  Screens ( sign up, sign in )

### ISSUE THREAD

**Issue by brianwachira** [droidconKE/droidconKE2022ReactNative#6]
**Description**
- From the design I presume one accesses these auth screens from home screen, hence the back buttons at the header

**Task**
- Create Sign Up Screens as per the guideline - [Sign up Design Adobe XD Link](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/588590d8-f833-4423-8ad8-7fdb79839d8e/specs/)
- Create Sign-In Screens as per the guideline - [Sign in Design Adobe XD Link](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/1871d761-8330-4b06-9dae-f8f1f8767046/specs/)
- Follow contribution guidelines laid out in our [contribution guide](https://github.com/droidconKE/droidconKE2022ReactNative/blob/develop/CONTRIBUTING.md)

**Additional context**
![Screenshot 2022-09-12 at 20 18 24](https://user-images.githubusercontent.com/28436092/189716626-0d503dfe-e4ed-4bae-9d81-a4f0debd168b.png)

![Screenshot 2022-09-12 at 20 18 47](https://user-images.githubusercontent.com/28436092/189716882-a9e0a290-d682-44db-9740-a402422d2dc0.png)

**Comment by DeroMuli** [comment]
I think I can pick this up. @makunomark  @brianwachira

**Comment by brianwachira** [comment]
> I think I can pick this up. @makunomark @brianwachira

@DeroMuli nice!
Lemme assign you the task.
Check out contribution guidelines and design guidelines.
 All the best!

**Comment by DeroMuli** [comment]
@brianwachira I can't seem to find the designs.

**Comment by brianwachira** [comment]
> @brianwachira I can't seem to find the designs.
- Sign up design link : [https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/588590d8-f833-4423-8ad8-7fdb79839d8e/specs/](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/588590d8-f833-4423-8ad8-7fdb79839d8e/specs/)
- Sign in design link : [https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/1871d761-8330-4b06-9dae-f8f1f8767046/specs/](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/1871d761-8330-4b06-9dae-f8f1f8767046/specs/)

Please revert back incase of any challenges.

**Comment by DeroMuli** [comment]
The sign up and sign in screen seem to be missing @brianwachira

**Comment by brianwachira** [comment]
> The sign up and sign in screen seem to be missing @brianwachira

please share a screenshot of what is seen when you access those links

**Comment by DeroMuli** [comment]
I am directed to the splash screen design
<img width="1680" alt="Screenshot 2022-09-19 at 12 26 17" src="https://user-images.githubusercontent.com/26671324/190988950-f24b8650-c4d3-4279-9001-fec271061919.png">

**Comment by brianwachira** [comment]
> I am directed to the splash screen design <img alt="Screenshot 2022-09-19 at 12 26 17" width="1680" src="https://user-images.githubusercontent.com/26671324/190988950-f24b8650-c4d3-4279-9001-fec271061919.png">

Noticed the same. Sorry about that. Lemme look into this

**Comment by brianwachira** [comment]
> 
> Noticed the same. Sorry about that. Lemme look into this

@DeroMuli So I have reached out to the droidconKE team and there has been some changes to the whole authentication process. 
DroidconKE team chose to have only a **Sign In using Google** modal that overlays the homescreen. Sorry for the inconvinience.

![image](https://user-images.githubusercontent.com/28436092/190995517-442633de-2e05-43b4-a734-f1138e4e3f73.png)

- Link : [https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/363ce570-c324-48cf-8582-e87a1d21ac82/specs/](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/363ce570-c324-48cf-8582-e87a1d21ac82/specs/)

**Comment by DeroMuli** [comment]
No worries
