### ISSUE TITLE
[UI] Configure App Splash Screen

### ISSUE THREAD

**Issue by brianwachira** [droidconKE/droidconKE2022ReactNative#7]
- Configure the app splash screen from the default expo splash screen to the one laid out on the [design](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/specs/) 
- Follow [contribution guidelines](https://github.com/droidconKE/droidconKE2022ReactNative/blob/develop/CONTRIBUTING.md) laid out in our contribution guide

**Additional context**
![Screenshot 2022-09-12 at 20 27 14](https://user-images.githubusercontent.com/28436092/189718215-919560ab-dded-49ce-8051-7ef7edda19df.png)

**Comment by mog-rn** [comment]
@brianwachira I'd like to also work on this one on top of what you had assigned me.

**Comment by brianwachira** [comment]
> @brianwachira I'd like to also work on this one on top of what you had assigned me.

Sure thing!
If you find any other that you would like to work on, you can go ahead and assign yourself the issue / task.
All the best!

**Comment by mog-rn** [comment]
ok great @brianwachira
