### ISSUE TITLE
[UI] Create Feeds Screen

### ISSUE THREAD

**Issue by brianwachira** [droidconKE/droidconKE2022ReactNative#8]
Create Feed Screen as per the guideline - [Feed Screen Design Adobe XD Link](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/aabbe326-f4d9-4fae-9cbc-433491567613/specs/)

Follow contribution guidelines laid out in our [contribution guide](https://github.com/droidconKE/droidconKE2022ReactNative/blob/develop/CONTRIBUTING.md)

![Screenshot 2022-09-12 at 21 14 34](https://user-images.githubusercontent.com/28436092/189726571-5de029db-a5b6-4839-afe4-bc43fdfb7813.png)

**Comment by mog-rn** [comment]
@brianwachira I can work on this before the session's screen is done

**Comment by brianwachira** [comment]
> @brianwachira I can work on this before the session's screen is done

If you are still up for this then go ahead!
Feel free to assign yourself this issue.
All the best!

**Comment by orama254** [comment]
Hello @Mogakamo ,

how is the progress for this issue?

any blockers that you may have encountered and would like assistance with?

**Comment by mog-rn** [comment]
@orama254 Hello,
I am doing well. I have been having issues getting to install the packages after I updated my local repo. I have also talked with @brianwachira but I don't know what is causing the issue. However, I will be able to make an update on my progress before the end of tomorrow incase I am not able to solve the issue

**Comment by brianwachira** [comment]
> @orama254 Hello, I am doing well. I have been having issues getting to install the packages after I updated my local repo. I have also talked with @brianwachira but I don't know what is causing the issue. However, I will be able to make an update on my progress before the end of tomorrow incase I am not able to solve the issue

@Mogakamo please share the issue you are getting on installing packages over here

**Comment by mog-rn** [comment]
`> droidconke2022reactnative@1.0.0 start C:\Users\Mogaka.dev\Desktop\droidconKE2022ReactNative
> expo start

internal/modules/cjs/loader.js:1088
  throw err;
  ^

Error: Cannot find module 'shebang-command'
Require stack:
- C:\Users\Mogaka.dev\Desktop\droidconKE2022ReactNative\node_modules\cross-spawn\lib\util\readShebang.js
- C:\Users\Mogaka.dev\Desktop\droidconKE2022ReactNative\node_modules\cross-spawn\lib\parse.js
- C:\Users\Mogaka.dev\Desktop\droidconKE2022ReactNative\node_modules\cross-spawn\index.js
- C:\Users\Mogaka.dev\Desktop\droidconKE2022ReactNative\node_modules\expo\bin\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.Module._load (internal/modules/cjs/loader.js:928:27)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\Users\Mogaka.dev\Desktop\droidconKE2022ReactNative\node_modules\cross-spawn\lib\util\readShebang.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Mogaka.dev\\Desktop\\droidconKE2022ReactNative\\node_modules\\cross-spawn\\lib\\util\\readShebang.js',
    'C:\\Users\\Mogaka.dev\\Desktop\\droidconKE2022ReactNative\\node_modules\\cross-spawn\\lib\\parse.js',
    'C:\\Users\\Mogaka.dev\\Desktop\\droidconKE2022ReactNative\\node_modules\\cross-spawn\\index.js',
    'C:\\Users\\Mogaka.dev\\Desktop\\droidconKE2022ReactNative\\node_modules\\expo\\bin\\cli.js'
  ]
}
 ELIFECYCLE  Command failed with exit code 1.
`

**Comment by Mogakamo** [comment]
`> droidconke2022reactnative@1.0.0 start C:\Users\Mogaka.dev\Desktop\droidconKE2022ReactNative
> expo start

internal/modules/cjs/loader.js:1088
  throw err;
  ^

Error: Cannot find module 'shebang-command'
Require stack:
- C:\Users\Mogaka.dev\Desktop\droidconKE2022ReactNative\node_modules\cross-spawn\lib\util\readShebang.js
- C:\Users\Mogaka.dev\Desktop\droidconKE2022ReactNative\node_modules\cross-spawn\lib\parse.js
- C:\Users\Mogaka.dev\Desktop\droidconKE2022ReactNative\node_modules\cross-spawn\index.js
- C:\Users\Mogaka.dev\Desktop\droidconKE2022ReactNative\node_modules\expo\bin\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.Module._load (internal/modules/cjs/loader.js:928:27)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (C:\Users\Mogaka.dev\Desktop\droidconKE2022ReactNative\node_modules\cross-spawn\lib\util\readShebang.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Mogaka.dev\\Desktop\\droidconKE2022ReactNative\\node_modules\\cross-spawn\\lib\\util\\readShebang.js',
    'C:\\Users\\Mogaka.dev\\Desktop\\droidconKE2022ReactNative\\node_modules\\cross-spawn\\lib\\parse.js',
    'C:\\Users\\Mogaka.dev\\Desktop\\droidconKE2022ReactNative\\node_modules\\cross-spawn\\index.js',
    'C:\\Users\\Mogaka.dev\\Desktop\\droidconKE2022ReactNative\\node_modules\\expo\\bin\\cli.js'
  ]
}
 ELIFECYCLE  Command failed with exit code 1.
`
@brianwachira @mark

**Comment by mog-rn** [comment]
@brianwachira @makunomark it's all clear the npm version that I was using was the one that was causing the errors. I am currently working on it now
